version: "3"

services:
  node-service:
    image: node:latest
    container_name: node
    volumes:
    - ./:/usr/src/react-boilerplate
    ports:
    - "3000:3000"
    command: tail -F anything
    working_dir: /usr/src/react-boilerplate/react-app